services:
  - type: web
    name: broker-property-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DATABASE_URL
        scope: build
        value: ${DATABASE_URL}
      - key: SECRET_KEY
        scope: build
        value: ${SECRET_KEY}
      - key: DEBUG
        value: "False"
      - key: DJANGO_ENV
        value: production
      - key: ALLOWED_HOSTS
        value: "broker-property-api.onrender.com"
      - key: CLOUDINARY_CLOUD_NAME
        scope: build
        value: ${CLOUDINARY_CLOUD_NAME}
      - key: CLOUDINARY_API_KEY
        scope: build
        value: ${CLOUDINARY_API_KEY}
      - key: CLOUDINARY_API_SECRET
        scope: build
        value: ${CLOUDINARY_API_SECRET}
