services:
  - type: web
    name: broker-property-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120
    healthCheckPath: /api/auth/csrf/
    envVars:
      - key: DJANGO_ENV
        value: production
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: broker-property-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: broker-property-api.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

databases:
  - name: broker-property-db
    plan: free
