# Generated by Django 4.2.7 on 2026-07-13 16:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyimage_local_or_cloud_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='property_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('document_type', models.CharField(choices=[('sale_deed', 'Sale Deed'), ('tax_receipt', 'Tax Receipt'), ('ownership_certificate', 'Ownership Certificate'), ('other', 'Other Documents')], default='other', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__place_067459_idx',
            old_name='properties_place_bhk_idx',
        ),
        migrations.RenameIndex(
            model_name='property',
            new_name='properties__status_8e4eb2_idx',
            old_name='properties_status_created_idx',
        ),
        migrations.RemoveField(
            model_name='property',
            name='advance',
        ),
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='olx_link',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='secondary_phone',
        ),
        migrations.AddField(
            model_name='property',
            name='house_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='property_video',
            field=models.FileField(blank=True, null=True, upload_to='property_videos/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bhk',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='square_feet',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], db_index=True, default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property'),
        ),
    ]
