import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import toast from 'react-hot-toast'
import { propertiesAPI } from '../api/endpoints'

const initial = { owner_name: '', primary_phone: '', whatsapp_number: '', place: '', area: '', complete_address: '', google_maps_link: '', instagram_link: '', bhk: '', floor: '', house_type: 'apartment', price: '', square_feet: '', parking: false, water_availability: '', power_backup: false, furnishing_status: 'unfurnished', facilities: '', description: '', broker_notes: '', status: 'available' }
const documents = ['sale_deed', 'tax_receipt', 'ownership_certificate', 'other']

export default function EditProperty() {
  const { id } = useParams(); const navigate = useNavigate()
  const [form, setForm] = useState(initial); const [images, setImages] = useState([]); const [video, setVideo] = useState(null); const [files, setFiles] = useState([]); const [types, setTypes] = useState([]); const [saving, setSaving] = useState(false)
  useEffect(() => { propertiesAPI.get(id).then(({ data }) => setForm({ ...initial, ...data })).catch(() => navigate('/properties')) }, [id, navigate])
  const change = ({ target }) => setForm(current => ({ ...current, [target.name]: target.type === 'checkbox' ? target.checked : target.value }))
  const submit = async (event) => { event.preventDefault(); setSaving(true); try { await propertiesAPI.update(id, { ...form, image_uploads: images, property_video: video, document_uploads: files, document_types: types }); toast.success('Property updated'); navigate(`/properties/${id}`) } catch (error) { toast.error(error.response?.data?.detail || 'Unable to update property') } finally { setSaving(false) } }
  const addDocuments = ({ target }) => { const selected = Array.from(target.files); setFiles(current => [...current, ...selected]); setTypes(current => [...current, ...selected.map(() => 'other')]) }
  return <main className="max-w-5xl mx-auto p-4 sm:p-6"><h1 className="mb-6 font-display text-3xl text-paper">Edit property</h1><form onSubmit={submit} className="space-y-6">
    <section className="card grid gap-4 md:grid-cols-2"><h2 className="form-wide font-display text-xl text-paper">Owner and location</h2>{[['owner_name','Owner name'],['primary_phone','Phone number'],['whatsapp_number','WhatsApp number'],['place','Place'],['area','Area'],['complete_address','Complete address'],['google_maps_link','Google Maps link'],['instagram_link','Instagram Link']].map(([name,label]) => <label key={name} className={name === 'complete_address' ? 'md:col-span-2' : ''}>{label}<input type={name.endsWith('_link') ? 'url' : 'text'} required={['owner_name','primary_phone','place','complete_address'].includes(name)} name={name} value={form[name] ?? ''} onChange={change} placeholder={name === 'instagram_link' ? 'https://instagram.com/username' : undefined} className="input" /></label>)}</section>
    <section className="card grid gap-4 md:grid-cols-2"><h2 className="md:col-span-2 font-display text-xl text-paper">Sale details</h2><label>Price<input required type="number" min="0" name="price" value={form.price ?? ''} onChange={change} className="input" /></label><label>BHK<input required type="number" min="1" name="bhk" value={form.bhk ?? ''} onChange={change} className="input" /></label><label>Floor<input type="number" name="floor" value={form.floor ?? ''} onChange={change} className="input" /></label><label>Square feet<input type="number" min="0" name="square_feet" value={form.square_feet ?? ''} onChange={change} className="input" /></label><label>House type<select name="house_type" value={form.house_type} onChange={change} className="input">{['apartment','villa','house','land','commercial'].map(value => <option key={value}>{value}</option>)}</select></label><label>Status<select name="status" value={form.status} onChange={change} className="input"><option value="available">Available</option><option value="sold">Sold</option></select></label><label>Furnishing<select name="furnishing_status" value={form.furnishing_status} onChange={change} className="input">{['unfurnished','semi-furnished','furnished'].map(value => <option key={value}>{value}</option>)}</select></label><label>Water availability<input name="water_availability" value={form.water_availability ?? ''} onChange={change} className="input" /></label><label><input type="checkbox" name="parking" checked={form.parking} onChange={change} /> Parking</label><label><input type="checkbox" name="power_backup" checked={form.power_backup} onChange={change} /> Power backup</label></section>
    <section className="card grid gap-4"><textarea name="facilities" value={form.facilities ?? ''} onChange={change} className="input" placeholder="Facilities" rows="3" /><textarea name="description" value={form.description ?? ''} onChange={change} className="input" placeholder="Description" rows="4" /><textarea name="broker_notes" value={form.broker_notes ?? ''} onChange={change} className="input" placeholder="Broker notes" rows="3" /></section>
    <section className="card grid gap-4 md:grid-cols-3"><label>Replace images<input type="file" accept="image/*" multiple onChange={e => setImages(Array.from(e.target.files).slice(0, 10))} /></label><label>Property video<input type="file" accept="video/*" onChange={e => setVideo(e.target.files[0] || null)} /></label><label>New documents<input type="file" multiple accept=".pdf,.doc,.docx,.jpg,.jpeg,.png" onChange={addDocuments} /></label>{files.map((file, index) => <label key={`${file.name}-${index}`} className="text-sm text-paper-dim">{file.name}<select value={types[index]} onChange={e => setTypes(current => current.map((type, itemIndex) => itemIndex === index ? e.target.value : type))} className="input">{documents.map(type => <option key={type}>{type}</option>)}</select></label>)}</section>
    <div className="flex gap-3"><button disabled={saving} className="btn-primary">{saving ? 'Saving…' : 'Save changes'}</button><button type="button" onClick={() => navigate(`/properties/${id}`)} className="btn-secondary">Cancel</button></div>
  </form></main>
}
